system_logger:
  level: debug
  destination: stdout
  formatter: text

ta:
  listen_addr: ":8843"
  ssl_cert: cert.pem
  ssl_cert_key: key.pem
  ca_certs_to_verify_client_certs:
    - ca.pem

pip:
  target_addr: "https://pip"